---
title: "p8105_hw2_gwk2111"
author: "Zach Keefer"
date: "9/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

##Problem 1

Read in data from the NYC transit subway entrance and exit data csv file, along with snaked variable names and entry converted from character to logical:

```{r}
nyc_transit_data = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, route1:route11, entrance_type, entry, vending, ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))

nyc_transit_data
```

Write something here

```{r}
nrow(distinct(nyc_transit_data, line, station_name, ada))

nrow(distinct(nyc_transit_data, line, station_name, ada) %>% 
        subset(ada == TRUE))

nrow(filter(nyc_transit_data, entry == TRUE, vending == "NO")) / nrow(filter(nyc_transit_data, vending == "NO"))
```

```{r}
nyc_transit_data_route_reformat = gather(nyc_transit_data, key = route_number, value = route_name, route1:route11)


nrow(distinct(nyc_transit_data_route_reformat, line, station_name, route_name) %>% 
       subset(route_name == "A"))


(nrow(distinct(nyc_transit_data_route_reformat, line, station_name, route_name, ada) %>% 
        filter(route_name == "A", ada == "TRUE")))
```

##Problem 2

Mr. Trash Wheel Sheet
```{r}
library(readxl)

mr_trash_wheel_data = 
  readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N258") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(sports_balls)) 
```

2016 and 2017 Precipitation Data
```{r}
prcp_2016 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2016 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  mutate(year = 2016)

prcp_2017 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = "2017 Precipitation", range = "A2:B14") %>% 
  janitor::clean_names() %>%
  filter(!is.na(total)) %>% 
  mutate(year = 2017)

prcp_2016_2017 = full_join(prcp_2016, prcp_2017) %>% 
  mutate(month = month.name[month])
```


##Problem 3
```{r}
library(p8105.datasets)

brfss_data = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  select(-class, -topic, -question, -sample_size, -(confidence_limit_low:geo_location)) %>% 
  spread(key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  mutate(prop_exc_vgood = excellent + very_good)
```

`r n_distinct(brfss_data$locationabbr)
